//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncomeManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IncomeManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _352_3529075_increase_revenue_sales_report_icon_png_transparent_png {
            get {
                object obj = ResourceManager.GetObject("352-3529075_increase-revenue-sales-report-icon-png-transparent-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3594376 {
            get {
                object obj = ResourceManager.GetObject("3594376", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51614549615yuhfzkrlsq {
            get {
                object obj = ResourceManager.GetObject("-51614549615yuhfzkrlsq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap business_performance_icon_trendy_flat_vector_performan_white_background_general_collection_illustration_can_be_use_web_130324335 {
            get {
                object obj = ResourceManager.GetObject("business-performance-icon-trendy-flat-vector-performan-white-background-general-c" +
                        "ollection-illustration-can-be-use-web-130324335", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_782_1093498 {
            get {
                object obj = ResourceManager.GetObject("coin-782-1093498", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coins_dollar_gold_sign_on_white_background_vector_25530348 {
            get {
                object obj = ResourceManager.GetObject("coins-dollar-gold-sign-on-white-background-vector-25530348", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cost_reduction_outline_icon_clipart_image_isolated_white_background_174417411 {
            get {
                object obj = ResourceManager.GetObject("cost-reduction-outline-icon-clipart-image-isolated-white-background-174417411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cost_reduction_outline_icon_clipart_image_isolated_white_background_1744174111 {
            get {
                object obj = ResourceManager.GetObject("cost-reduction-outline-icon-clipart-image-isolated-white-background-1744174111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollar_rate_increase_icon_money_symbol_stretching_arrow_up_rising_prices_business_cost_sale_cash_salary_investment_growth_133977816 {
            get {
                object obj = ResourceManager.GetObject("dollar-rate-increase-icon-money-symbol-stretching-arrow-up-rising-prices-business" +
                        "-cost-sale-cash-salary-investment-growth-133977816", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollar_rate_increase_icon_money_symbol_stretching_arrow_up_rising_prices_business_cost_sale_cash_salary_investment_growth_1339778161 {
            get {
                object obj = ResourceManager.GetObject("dollar-rate-increase-icon-money-symbol-stretching-arrow-up-rising-prices-business" +
                        "-cost-sale-cash-salary-investment-growth-1339778161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap income_icon_vector_isolated_white_background_logo_concept_income_icon_vector_isolated_white_background_logo_concept_125781266 {
            get {
                object obj = ResourceManager.GetObject("income-icon-vector-isolated-white-background-logo-concept-income-icon-vector-isol" +
                        "ated-white-background-logo-concept-125781266", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Income_PNG_Free_Download {
            get {
                object obj = ResourceManager.GetObject("Income-PNG-Free-Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Income_PNG_Free_Download1 {
            get {
                object obj = ResourceManager.GetObject("Income-PNG-Free-Download1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Income_PNG_Free_Download2 {
            get {
                object obj = ResourceManager.GetObject("Income-PNG-Free-Download2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Income_PNG_Free_Download3 {
            get {
                object obj = ResourceManager.GetObject("Income-PNG-Free-Download3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1188230265_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1188230265-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line_cash_dollar_money_icon_on_white_background_vector_17683123 {
            get {
                object obj = ResourceManager.GetObject("line-cash-dollar-money-icon-on-white-background-vector-17683123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout_icon_in_trendy_blue_eyes_style_isolated_on_soft_blue_background_free_vector {
            get {
                object obj = ResourceManager.GetObject("logout-icon-in-trendy-blue-eyes-style-isolated-on-soft-blue-background-free-vecto" +
                        "r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_earnings_finance_tax_profit_revenue_growthing_money_text_investment_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-clipart-earnings-finance-tax-profit-revenue-growthing-money-text-investment-t" +
                        "humbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_earnings_finance_tax_profit_revenue_growthing_money_text_investment_thumbnail1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-earnings-finance-tax-profit-revenue-growthing-money-text-investment-t" +
                        "humbnail1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vector_dollars_coin_icon_png_image_4142461 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vector-dollars-coin-icon-png-image_4142461", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vector_dollars_coin_icon_png_image_850597 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vector-dollars-coin-icon-png-image_850597", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap salary_cash {
            get {
                object obj = ResourceManager.GetObject("salary-cash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap salary_day_money {
            get {
                object obj = ResourceManager.GetObject("salary-day-money", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__227_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (227)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__228_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (228)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__229_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (229)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot__230_ {
            get {
                object obj = ResourceManager.GetObject("Screenshot (230)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap social_media_icons_black_colored_icon_set_vector_36503710 {
            get {
                object obj = ResourceManager.GetObject("social-media-icons-black-colored-icon-set-vector-36503710", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
